"""
GCHS GenAI Use Case - Augmentation Techniques and Evaluation Metrics
"""

# --- Augmentation Techniques Prompts ---

paraphrasing_prompt = '''
You are a regulatory documentation specialist. Take the following complaint narrative for a medical device incident, as entered into the Olympus Global Complaint Handling System (GCHS), and create a new version that:
- Retains all facts necessary for MDR/IMDRF code assignment under 21 CFR Part 803.
- Presents details using substantially different wording, grammar, sentence structure, and alternate terminology (e.g., synonyms, technical terms, clinical language, or plain English).
- Could plausibly serve as a different complaint record for validation testing.

Original complaint:
{original_complaint_text}

Produce only the paraphrased version appropriate for GCHS submission.
'''

broken_english_prompt = '''
Simulate a GCHS medical device complaint from a user whose first language is not English. Rewrite the event narrative below to include:
- Frequent grammar/disagreement errors, spelling mistakes, article/preposition confusion.
- Use of basic vocabulary and shortened sentences.
- Realistic misunderstandings or unclear phrasing found in multinational regulatory complaint datasets.

Original complaint:
{original_complaint_text}

Return the new, linguistically challenged narrative for model robustness testing.
'''

sequence_alterations_prompt = '''
Reshuffle the following complaint so that the order of facts, events, and procedural details is significantly different from the original timeline. Mimic real-world disorder by:
- Beginning with the outcome or a non-sequitur.
- Describing events non-chronologically, jumping between steps or repeating details in a confusing way.
- Maintaining all original information for regulatory/evaluation purposes.

Original complaint:
{original_complaint_text}

Return the temporally disordered complaint.
'''

tone_variation_prompt = '''
Rewrite the following complaint in the voice of a specific GCHS user persona: [Clinical engineer | Nurse | Concerned relative | Hospital administrator].  
- Use vocabulary, sentence length, and focus areas representative of that persona (e.g., technical specifics, emotional tone, focus on patient or process).
- Ensure the rewritten complaint is realistic for MDR review and testing field diversity.

User persona: {chosen_persona}
Original complaint:
{original_complaint_text}

Return the persona-aligned narrative for model testing.
'''

multi_intent_prompt = '''
Imagine that a complaint owner has submitted two related device incidents as a single complaint, in line with the complexity found in real-world GCHS operations. Blend the two narratives below into a coherent, compound complaint that:
- Articulates both events with sufficient detail for IMDRF field testing.
- Merges sequence and context naturally, highlighting how the issues may relate or follow from each other.

Complaint #1: {complaint_text_1}
Complaint #2: {complaint_text_2}

Return the merged complaint for multi-intent extraction testing.
'''

# --- Evaluation Metrics Prompts ---

per_code_accuracy_prompt = '''
You are an MDR auditor. Compare the GenAI-determined IMDRF codes for A, E, and F fields against ground truth for this complaint. For each code, state "Exact match: YES/NO". If NO, specify why, citing narrative evidence.

Complaint: {complaint_text}
GenAI codes: A: {ai_a_code}, E: {ai_e_code}, F: {ai_f_code}
Ground truth: A: {gt_a_code}, E: {gt_e_code}, F: {gt_f_code}

Report match verdicts with reasons if mismatched.
'''

justification_coherence_prompt = '''
As a domain expert, assess the logic and relevance of the following GenAI rationale for its code assignment.  
- Does it clearly explain how narrative facts led to code selection?
- Are clinical and procedural links accurate and specific (not general)?
- Score from 1 (not connected/confusing) to 5 (explicit, reasoned, direct citations from the complaint).

Complaint: {complaint_text}
Rationale: {genai_justification}

Provide score, explanation, and highlight key sentence for review.
'''

field_format_validation_prompt = '''
Check that the following GenAI output for a GCHS complaint:
- Populates all mandatory fields (Usage of Device, Device Operator, Procedure Name, Procedure Type, Procedure Outcome, Patient Outcome).
- Leaves no field empty or skipped, and uses expected format per SOP.

Fields: {fields_json}

For each field, mark: [Populated: YES/NO] [Format: OK/ERROR]; explain if NOT OK.
'''

invalid_code_detection_prompt = '''
Cross-validate the following IMDRF codes generated by GenAI against the official IMDRF list.  
List each suggested code, stating clearly if it does not appear in the official list and flagging it as "INVALID - Not recognized". At the end, summarize number of invalid codes.

GenAI codes: {predicted_codes_list}
IMDRF official codes: {imdrf_code_list}
'''

instruction_adherence_prompt = '''
Audit the GenAI-generated output for this GCHS complaint against the agent workflow and MDR requirements listed below.  
- Did the system fill all required fields and follow population guidelines?
- Did it transition complaint from 'Open' to 'Complaint In Progress' as specified?
- Were MDR-specific procedural fields and expected outputs created in alignment with the workflow?

Instructions: {instruction_summary}
GenAI output: {output_content}

Return overall verdict (Adhered: YES/NO), then specifically list any deviations noted.
'''

